# Generated by Django 4.2.1 on 2023-05-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('URL_ubicacion', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('URL_instagram', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('id_datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.datosservicios')),
            ],
            options={
                'verbose_name': 'Categoría de servicios',
                'verbose_name_plural': 'Categorías de servicios',
            },
        ),
    ]
